language: java


jdk:
  - openjdk8
  - openjdk11
  - openjdk17

script:
  - lsb_release -a
  - uname -a
  - java -version
  - cd tools/java/crcl4java
  - mvn -version
  - mvn -U verify
  
notifications:
  email:
    - william.shackleford@nist.gov
    - wshackle@gmail.com


