language: java


jdk:
  - oraclejdk8
  - oraclejdk11
  

script:
  - java -version
  - cd tools/java/crcl4java
  - mvn -version
  - mvn -U test
  
notifications:
  email:
    - william.shackleford@nist.gov
    - wshackle@gmail.com


