language: java


jdk:
  - oraclejdk8
  - oraclejdk10
  

script:
  - java -version
  - cd tools/java/crcl4java
  - mvn -version
  - mvn -X -Pwith_checkers -U test
  
notifications:
  email:
    - william.shackleford@nist.gov
    - wshackle@gmail.com


